"""Export scan results as a MITRE ATT&CK Navigator layer.

A "layer" is a small JSON document that the ATT&CK Navigator web app
(https://mitre-attack.github.io/attack-navigator/) renders as a coloured
heatmap of the matrix. Each detected technique is coloured by the highest
severity that referenced it and scored by the summed finding weights.
"""

from __future__ import annotations

import datetime as _dt
import json

from . import __version__
from .analyzers.base import SEVERITIES, SEVERITY_WEIGHT
from .attack import tactic
from .scanner import ScanResult

DOMAIN = "enterprise-attack"
ATTACK_VERSION = "15"

SEVERITY_COLOR = {
    "critical": "#e11d48",
    "high": "#f97316",
    "medium": "#eab308",
    "low": "#38bdf8",
    "info": "#94a3b8",
}

_SEVERITY_RANK = {name: index for index, name in enumerate(SEVERITIES)}


def _aggregate(results: list[ScanResult]) -> dict[str, dict]:
    techniques: dict[str, dict] = {}
    for result in results:
        for finding in result.findings:
            for technique_id in finding.attack:
                entry = techniques.setdefault(
                    technique_id,
                    {"severity": "info", "score": 0, "comments": []},
                )
                entry["score"] += SEVERITY_WEIGHT.get(finding.severity, 0)
                if _SEVERITY_RANK[finding.severity] > _SEVERITY_RANK[entry["severity"]]:
                    entry["severity"] = finding.severity
                entry["comments"].append(f"{result.filename}: {finding.message}")
    return techniques


def build_layer(results: list[ScanResult], name: str | None = None) -> dict:
    """Build an ATT&CK Navigator layer (format 4.5) from scan results."""
    techniques = _aggregate(results)

    entries = []
    for technique_id, data in techniques.items():
        comment = "\n".join(dict.fromkeys(data["comments"]))
        entries.append(
            {
                "techniqueID": technique_id,
                "tactic": tactic(technique_id),
                "color": SEVERITY_COLOR.get(data["severity"], "#94a3b8"),
                "score": min(100, data["score"]),
                "enabled": True,
                "comment": comment,
            }
        )
    entries.sort(key=lambda item: (-item["score"], item["techniqueID"]))

    present = {data["severity"] for data in techniques.values()}
    legend = [
        {"label": severity, "color": SEVERITY_COLOR[severity]}
        for severity in ("critical", "high", "medium", "low", "info")
        if severity in present
    ]

    return {
        "name": name or f"Larvanex: {len(results)} file(s)",
        "versions": {"attack": ATTACK_VERSION, "navigator": "4.9", "layer": "4.5"},
        "domain": DOMAIN,
        "description": (
            f"Generated by Larvanex {__version__} on "
            f"{_dt.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}. Static analysis only."
        ),
        "techniques": entries,
        "gradient": {"colors": ["#f8fafc", "#e11d48"], "minValue": 0, "maxValue": 100},
        "legendItems": legend,
        "showTacticRowBackground": True,
        "tacticRowBackground": "#1f2937",
        "selectTechniquesAcrossTactics": True,
    }


def render_layer(results: list[ScanResult], name: str | None = None) -> str:
    return json.dumps(build_layer(results, name=name), indent=2)
